# Generated by Django 3.1.12 on 2024-06-26 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_agent_user_supportticket_user_id_supportticket_agent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='is_active',
            new_name='is_available',
        ),
    ]
