# Generated by Django 4.2.7 on 2024-06-27 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20240626_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportticket',
            old_name='agent',
            new_name='assigned_agent',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='user_id',
        ),
        migrations.AddField(
            model_name='supportticket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.user'),
        ),
    ]
