# Generated by Django 4.2.7 on 2024-06-27 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_rename_agent_supportticket_assigned_agent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticket',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='email',
        ),
    ]
