# Generated by Django 4.2.7 on 2024-06-28 05:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_supportticket_customer_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedTicket',
            fields=[
                ('ticket_id', models.CharField(editable=False, max_length=36, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(default='closed', max_length=50)),
                ('created_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(default=datetime.datetime.now)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.agent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.user')),
            ],
        ),
    ]
